#!/bin/sh
set -x

wclean oversetMesh
wclean oversetDynamicFvMesh

wclean laplacianOversetFoam
wclean potentialOversetFoam
wclean scalarTransportOversetFoam
wclean icoOversetFoam
wclean simpleOversetFoam
wclean interOversetFoam

wclean potentialDyMOversetFoam
wclean icoDyMOversetFoam
wclean pimpleDyMOversetFoam

wclean oversetRegionIndex
wclean calcOverset 
