#!/bin/sh
set -x

wmake libso oversetMesh
wmake libso oversetDynamicFvMesh

wmake laplacianOversetFoam
wmake potentialOversetFoam
wmake scalarTransportOversetFoam
wmake icoOversetFoam
wmake simpleOversetFoam
wmake interOversetFoam

wmake potentialDyMOversetFoam
wmake icoDyMOversetFoam
wmake pimpleDyMOversetFoam

wmake oversetRegionIndex
wmake calcOverset 
